### Register / login
POST {{baseUrl}}/public/auth/signin
Content-Type: application/json

{
  "username": "rafael2",
  "password": "abcdef"
}

> {%
    client.global.set("authToken", response.body.jwt);
%}